name: Playwright Tests & Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
    steps:
    - uses: actions/checkout@v4
    # THIS IS THE CORRECTED LINE
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        BASE_URL: https://demoblaze.com/index.html
        TEST_USERNAME: pavanol
        TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
      run: npx playwright test --shard=${{ matrix.shard }}/${{ strategy.job-total }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.shard }}
        path: playwright-report/
        retention-days: 7

  publish-report:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Download all test reports
        uses: actions/download-artifact@v4
        with:
          path: all-reports

      - name: Merge reports
        run: |
          mkdir playwright-merged-report
          npx playwright merge-reports --reporter html ./all-reports --output playwright-merged-report/

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload merged report artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-merged-report/
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
